language: php

# Versi PHP
php:
  - 7.2

# Branch yang digunakan
branches:
  only:
    - master #-> QA/Staging server
    - develop #-> DevServer

# Precompile
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

# Main Execution (Build)
script:
  - ./vendor/bin/phpunit